language: java
jdk:
 - openjdk8
script: mvn clean install --batch-mode
matrix:
  allow_failures:
    - jdk: openjdk8
branches:
  only:
    - master
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#openmrs"
    template:
      - "[%{repository}] [%{commit}] [%{author}] %{message} - %{build_url}"

